### ISSUE TITLE
Inconsistencies in units of energy in models.py

### ISSUE THREAD

**Issue by nuberoi** [SNEWS2/snewpy#29] opened 2021-02-12 00:49 UTC
The method `get_initialspectra` inside the model classes uses seems to apply the log function to an `astropy.Quantity` term, leading to a `UnitTypeError` and a `UnitConversionError` when the notebook `Flavor_XForm.ipynb` is run.

**Comment by sybenzvi** [comment] 2021-02-12 15:42
I can't reproduce this issue, and I am definitely using the current checkout of the main branch. You may need to double-check your user environment @nuberoi... something suspicious is going on.

**Comment by nuberoi** [comment] 2021-02-12 16:03
Exact error message:

---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
c:\programdata\anaconda3\lib\site-packages\astropy\units\quantity_helper\helpers.py in get_converter(from_unit, to_unit)
     31     try:
---> 32         scale = from_unit._to(to_unit)
     33     except UnitsError:

c:\programdata\anaconda3\lib\site-packages\astropy\units\core.py in _to(self, other)
    950         raise UnitConversionError(
--> 951             f"'{self!r}' is not a scaled version of '{other!r}'")
    952 

UnitConversionError: 'Unit("erg / s")' is not a scaled version of 'Unit(dimensionless)'

During handling of the above exception, another exception occurred:

UnitConversionError                       Traceback (most recent call last)
c:\programdata\anaconda3\lib\site-packages\astropy\units\quantity_helper\helpers.py in helper_dimensionless_to_dimensionless(f, unit)
    146     try:
--> 147         return ([get_converter(unit, dimensionless_unscaled)],
    148                 dimensionless_unscaled)

c:\programdata\anaconda3\lib\site-packages\astropy\units\quantity_helper\helpers.py in get_converter(from_unit, to_unit)
     34         return from_unit._apply_equivalencies(
---> 35                 from_unit, to_unit, get_current_unit_registry().equivalencies)
     36     except AttributeError:

c:\programdata\anaconda3\lib\site-packages\astropy\units\core.py in _apply_equivalencies(self, unit, other, equivalencies)
    887             "{} and {} are not convertible".format(
--> 888                 unit_str, other_str))
    889 

UnitConversionError: 'erg / s' (power) and '' (dimensionless) are not convertible

During handling of the above exception, another exception occurred:

UnitTypeError                             Traceback (most recent call last)
<ipython-input-8-3405dee786df> in <module>
----> 1 fig = plot_spec(model, NoTransformation)

<ipython-input-6-d3b68cffa269> in plot_spec(model, flav_xform, t, E, check_imo)
     23 
     24     # Compute the initial and oscillated spectra.
---> 25     ispec = model.get_initialspectra(t, E)
     26     ospec_nmo = model.get_oscillatedspectra(t, E, xform_nmo)
     27     ospec_imo = model.get_oscillatedspectra(t, E, xform_imo)

c:\users\navya uberoi\documents\git\snewpy\python\snewpy\models.py in get_initialspectra(self, t, E)
    222             initialspectra[flavor] = \
    223                 np.exp(np.log(L) - (2+a)*np.log(Ea) + (1+a)*np.log(1+a) 
--> 224                        - loggamma(1+a) + a*np.log(E) - (1+a)*(E/Ea))
    225 
    226         return initialspectra

c:\programdata\anaconda3\lib\site-packages\astropy\units\quantity.py in __array_ufunc__(self, function, method, *inputs, **kwargs)
    455         # consistent units between two inputs (e.g., in np.add) --
    456         # and the unit of the result (or tuple of units for nout > 1).
--> 457         converters, unit = converters_and_unit(function, method, *inputs)
    458 
    459         out = kwargs.get('out', None)

c:\programdata\anaconda3\lib\site-packages\astropy\units\quantity_helper\converters.py in converters_and_unit(function, method, *args)
    164 
    165         # Determine possible conversion functions, and the result unit.
--> 166         converters, result_unit = ufunc_helper(function, *units)
    167 
    168         if any(converter is False for converter in converters):

c:\programdata\anaconda3\lib\site-packages\astropy\units\quantity_helper\helpers.py in helper_dimensionless_to_dimensionless(f, unit)
    150         raise UnitTypeError("Can only apply '{}' function to "
    151                             "dimensionless quantities"
--> 152                             .format(f.__name__))
    153 
    154 

UnitTypeError: Can only apply 'log' function to dimensionless quantities

**Comment by sybenzvi** [comment] 2021-02-15 18:00
Fixed by checking for code that uses `astropy.Quantity` objects and extracting their values.

**Closed by sybenzvi** 2021-02-15 18:00 UTC
Labels: bug
