### ISSUE TITLE
Check that no proprietary models or code are in the repository

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/snewpy#23] opened 2020-10-20 15:37 UTC
Before the repository goes public, check that it includes no proprietary flux models or unlicensed code.

**Comment by sybenzvi** [comment] 2021-02-12 16:17
@jpkneller and @evanoconnor, I'd like to close this out. Should we just delete whatever 'Janka' is then?

**Comment by jpkneller** [comment] 2021-02-12 16:41
We have permission to use them, the issue is what some of these models are exactly and where they come from. The filenames indicate some use the SFHo and Shen EOS but Thomas Ertl says the Garching group never uses those EOSs, they usually use LS220. I am comfortable including the LS220 models because we can point to a paper, the others should probably be scrubbed.

**Comment by JostMigenda** [comment] 2021-07-27 11:48
Closed by @sybenzvi in #48.

**Closed by JostMigenda** 2021-07-27 11:48 UTC
Labels: help wanted
